# Useful Commands:
# docker build . -t mortgage-backend:latest -f ci/Dockerfile
# docker-compose -p mortgage-backend -f ci/docker-compose.yaml up

version: '3.9'

services:
  mortgage-backend:
    image: mortgage-backend:latest
    container_name: mortgage-backend
    user: node:node
    ports:
      - 3000:3000
    env_file: ../.env
    environment:
      NODE_ENV: production
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:3000/api/healthz || exit 1
      interval: 1m
      start_period: 5s
      timeout: 10s
      retries: 3
